#!/usr/bin/env python3
# -*- coding: utf-8 -*-


path: /Users/louisepoteau/Documents/Phelma/SICOM/S8/Projet_Collectif/ReconnaissancePanneaux/data
train: images/train
val: images/train

#Classes
names:
    0: StopSign